### ISSUE TITLE
Real-time preview of changes

### ISSUE THREAD

**Issue by asirota** [NewPath-Consulting/watm#100]
Currently any changes to the config files need to be uploaded to see the changes be applied for good. 

Let's have a way to "preview" changes made on the Browser window for every change. Then a visual indicator should show that the file needs to be saved, maybe by removing the save to site button until a change has been made to a config file. 

It should be possible to go into a preview mode and then turn it off too.

**Comment by mDisna** [comment]
saving now does a server-refresh, and is relatively fast. Is this really needed?

there would need to be a way to undo what has already been implemented with the csv, and then re-run all the scripts to implement what's in the table. In terms of the text-changes, I don't think this would be possible,

**Comment by asirota** [comment]
this would be more of a troubleshooting thing to apply to only one line of a config.. Helpful when working to troubleshoot something in terms of a query or function. A little UI cue to execute just one line before saving.

**Comment by mDisna** [comment]
This would only be able to apply to styles, and it won't be possible to revert it without refreshing the page/exiting.

**Comment by asirota** [comment]
Why not? Can't the JavaScript in WATM that normally loads on page be triggered temporarily to make a text change and then be turned off? What's technically stopping a piece of text being changed vs a style being changed?

**Comment by mDisna** [comment]
With the way the code is organized, I can't call those functions from the editor. Even, if I could, that code only works with CSV files. I would need to write a new code to have it work on one line that's in memory. I can do this if you really want it, I just think it'll cause bloat to the code - especially considering it's a one-way change. It's not possible to undo the change without refreshing - so there is a refresh either way.

**Comment by asirota** [comment]
Something to continue to think about I guess. Maybe the current workflow works best since the save is so fast anyways.
