### ISSUE TITLE
Fix issue where watm language cookie is not being read

### ISSUE THREAD

**Issue by asirota** [NewPath-Consulting/watm#103]
[Does this apply to our cookies that we set in watm?](https://blog.chromium.org/2019/10/developers-get-ready-for-new.html)

**Comment by mDisna** [comment]
This was implemented in the [last commit](https://github.com/NewPath-Consulting/watm/commit/ab3ac09ab51ac87ff89b63d64fb7cf1baa0f6006) on all branches.
