### ISSUE TITLE
Introduce a fontawesome function

### ISSUE THREAD

**Issue by asirota** [NewPath-Consulting/watm#107]
[fontawesome](https://fontawesome.com/v6/docs/web/setup/get-started) is well... awesome! It's a really easy way to introduce iconography from 10,000+ icons with all sorts of variants, animations and layering/styling. For free FontAwesome Free gives you 2000+ icons that can be used simply by 

a) attaching a JS to your <head>
b) adding a fa-<iconname> style to your elements (eg the `<i>` element)
c) optionally you can add fa-<styling> tokens to create animations, etc.

a new Fontawesome function could

a) target an element
b) the style column  would be the place to add an icon (or several)

These are really useful on buttons, so it's possible that the button function could have some fontawesome options as well with an option to add the icon to the left or the right of the text

**Comment by mDisna** [comment]
I've thought about this quite a bit. I think adding FontAwesome the way FA needs you to is too complex for the EZ designer target audience. If requires going in to the HTML and pasting in the FA HTML code in the correct location. It's further complicated by the fact that Wild Apricot does not allow you to add empty containers, so the code would need to be modified. For example, to add the home icon, FA needs you to paste in:

```<i class="fa-solid fa-house"></i>```

However, this will not work in WA - you would need to paste in:

```<i class="fa-solid fa-house">&nbsp;</i>```

So in thinking about how to simplify the process, the the best solution would be to create macros.

**Comment by mDisna** [comment]
Future improvements will be to add attributes for the icon type.

Example: `[fa type="brand"]facebook[/fa]`

And yes, this can be adapted to add macros for other things, such as custom widgets.

Example: `[EZ:twitter]@newpathtech[/EZ:twitter]`

**Comment by asirota** [comment]
I like the idea of actually having an ez- prefix to our macros. like ez-fa for fontawesome. ez-<functionname> would be nice. Can we change that?

**Comment by mDisna** [comment]
@asirota yes, I've made this change in the branch I'm working on. Will push it soon.
