### ISSUE TITLE
Inspector logo for showing license key state

### ISSUE THREAD

**Issue by asirota** [NewPath-Consulting/watm#71]
Default logo

![image](https://user-images.githubusercontent.com/458134/172407269-b2a6e15f-0b87-422b-98b2-edb7c045545d.png)

licensed logo

![image](https://user-images.githubusercontent.com/458134/172407381-3741beeb-3fb1-4d88-ab59-b19437549cab.png)

trial logo

![image](https://user-images.githubusercontent.com/458134/172407418-d48d8199-1b8c-40d2-881d-0e642ae4fae7.png)

invalid key logo

![image](https://user-images.githubusercontent.com/458134/172407491-9641e2cd-73b2-46bc-ba46-9b77e85679e0.png)

@mDisna have a look and see if these work for you...

**Comment by mDisna** [comment]
Implemented in latest 2.0 branch push
In addition, inspector & editor are  now only accessible to logged in administrators.
