### ISSUE TITLE
pattern matching issue

### ISSUE THREAD

**Issue by mklybor** [NewPath-Consulting/watm#73]
I have been having problems matching patterns (for a replace) for text that contains punctuation marks (hyphen and parenthesis in particular). It doesn't match those patterns, and doesn't find the text to replace. In these situation, the punctuation marks are important to find the right text that needs to be replaced.

**Comment by asirota** [comment]
According to @mDisna you can escape certain characters like - with a `\` character. We should document which other characters need to be escaped this way.
