### ISSUE TITLE
when no language_switcher element found, WATM crashes

### ISSUE THREAD

**Issue by asirota** [NewPath-Consulting/watm#77]
when there is no language_swticher element found, WATM 2.0 crashes with

functions.js:77
       Uncaught (in promise) TypeError: Cannot read properties of null (reading 'parentNode')
    at createToggle (functions.js:77:19)
    at start (wildapricot-textmanager.js:112:9)
    at functions.js:37:9

in console

If the multilingual features are turned on, and the languageswitcher element defined in JS (or the default language_switcher) is not found, present an error message.

No language switcher content gadget found. Add a content gadget with class `language_switcher` to all of your page templates.

replace language_switcher to the class defined in the global JS if any, or default

**Comment by mDisna** [comment]
Latest fix adds warning to console. and also allows the site to continue as if  `var showLanguageSwitch = false;` was used - it's possible users may not want the toggle on specific pages

**Comment by asirota** [comment]
I tested with latest code and still getting the error when the language_switcher gadget is missing or has the wrong ID


functions.js:77 
        
       Uncaught (in promise) TypeError: Cannot read properties of null (reading 'parentNode')
    at createToggle (functions.js:77:19)
    at start (wildapricot-textmanager.js:112:9)
    at functions.js:37:9

**Comment by mDisna** [comment]
Ah, sorry - forgot to push to changes to GH
Please try again

**Comment by asirota** [comment]
this works fine now
