### ISSUE TITLE
Licensed WATM shows console log that it is in trial

### ISSUE THREAD

**Issue by asirota** [NewPath-Consulting/watm#81]
![image](https://user-images.githubusercontent.com/458134/179353864-e7b17c5e-1f70-4247-bf8e-4aa637e71529.png)

**Comment by mDisna** [comment]
@asirota 

Are you using the testing key?
The script is currently using the dev url to validate the key.

**Comment by asirota** [comment]
Yes I'm using the Testing key

**Comment by asirota** [comment]
To be sure, this happens when I switch to French language with the language switcher.

**Comment by mDisna** [comment]
Issue lies in sample french.csv file. This file has been updated in the repo.

Will work on better error checking and reporting.
