### ISSUE TITLE
Integrate new Licensed and Invalid License inspector icons

### ISSUE THREAD

**Issue by asirota** [NewPath-Consulting/watm#82]
I got some feedback that the licensed and invalid logos are not good indicators of license status. So I made some new ones. I also included a blank logo in case we need to make new variants
<img width="18" alt="ez invalid v2" src="https://user-images.githubusercontent.com/458134/179776659-ba16e404-b041-4eeb-9092-4cbf249d4033.png">
<img width="18" alt="ez licensed v2" src="https://user-images.githubusercontent.com/458134/179776662-f64b8648-c478-4547-8efc-ec55f2c94a13.png">
<img width="18" alt="ez blank" src="https://user-images.githubusercontent.com/458134/179776663-1a3a75d7-5f92-40c7-a243-cabf11219bda.png">
.

**Comment by mDisna** [comment]
These will not work. They are too small and need to be transparent.

I will remake them.

**Comment by mDisna** [comment]
These are the existing icons

![active](https://user-images.githubusercontent.com/21189988/179778686-596ce909-a5e3-46c8-af83-f2bce7f482b1.png)
![default](https://user-images.githubusercontent.com/21189988/179778687-3c5ee8c5-363c-483d-b845-f8060bb10470.png)
![invalid](https://user-images.githubusercontent.com/21189988/179778688-4421cdac-e5e9-416e-8bc9-7b896a16cfa1.png)
![trial](https://user-images.githubusercontent.com/21189988/179778689-823cb20c-9bb3-4d49-87ba-82dce71a53eb.png)

**Comment by mDisna** [comment]
@asirota  Since the new icons are simply a checkmark and ex, should we use this to display other errors too? Currently errors are only visible if you open the console.

**Comment by asirota** [comment]
If you want to open a special EZ Website Designer Log Console from the popup icon that could work. But let's leave it to a future version for now.

**Comment by asirota** [comment]
<img width="23" alt="invalid with x" src="https://user-images.githubusercontent.com/458134/179809349-22e934aa-09d6-446a-9db2-774c5369bbc4.png">
<img width="23" alt="active with check" src="https://user-images.githubusercontent.com/458134/179809353-d053b998-33f9-49df-a401-ab2ed50618f4.png">

new active and invalid icons - can leave default and T for trial as is

**Comment by mDisna** [comment]
Icons have been updated.
