### ISSUE TITLE
langauge switcher label must show currently selected language

### ISSUE THREAD

**Issue by asirota** [NewPath-Consulting/watm#91]
the language switcher goes back to select a language once you switched to english or french. It should reflect the currently selected language

**Comment by mDisna** [comment]
note: you can translate the "Select language" text - on my test site, the message is translated to the current language - but you can also replace the text with the language name using the CSV.

**Comment by asirota** [comment]
@mDisna not sure if that is a solution as a base case considering they already provided the translated langauge "slugs"... But yes i can see what you mean.
