### ISSUE TITLE
trying to adjust link of footer text, but it does not work

### ISSUE THREAD

**Issue by asirota** [NewPath-Consulting/watm#92]
I edited the link for Wild Apricot in the footer text, but no matter what I do I cannot get the link to change. See screen shot where I am hovering over the link. I am testing in trial mode by the way, same goes for Licensed mode

![image](https://user-images.githubusercontent.com/458134/180561010-63f0a0f6-33b4-455a-b25f-fa5da8b06038.png)

**Comment by mDisna** [comment]
This is working on my site using the same query.

See if clearing your browser cache updates the link

**Comment by asirota** [comment]
Yeah maybe it was cache related the css path was #id a (space after #id)
