### ISSUE TITLE
file editor -> add new row, delete row

### ISSUE THREAD

**Issue by asirota** [NewPath-Consulting/watm#94]
Like in a spreadsheet there will need to be a way to add a new row and delete a row for management of the files. A duplicate row would be helpful too.

**Comment by mDisna** [comment]
There is currently a button at the bottom of the table to add a new row. A row can be deleted by setting each cell to be blank.

I will add a dedicated delete button, and the ability to add a row to any point in the table.

**Comment by asirota** [comment]
Is there way to delete a row in the new editor?

**Comment by mDisna** [comment]
Yes, this can be done by right clicking on the row and clicking "Delete Selected Rows" in the context menu

**Comment by asirota** [comment]
I see that. Even copy and paste works!
